### ISSUE TITLE
Searching for 2 or more words returns double statement on the UI

### ISSUE THREAD

**Issue by cyntss** [EOS-uiux-Solutions/eos-icons-landing#1]
![image](https://user-images.githubusercontent.com/5013096/120190174-887f9b80-c218-11eb-88da-107732ac0763.png)

Steps to reproduce the issue:

- Enter "Flight Class".
- The UI will return the fetched results after entering "flight" but after the blank space and the new word, it seems it is performing a new search and returning the empty results all on the same screen.

Expected behavior:

- All items matching the keywords "flight" and/or "class" should be returned as matching results.

**Comment by codetheorem** [comment]
I want to work on this issue.

**Comment by vinayaksh42** [comment]
@codetheorem This is actually a duplicate issue. This issue is listed as issue #5 - https://github.com/EOS-uiux-Solutions/eos-icons-landing/issues/5
