### ISSUE TITLE
Animated icons Bug: The search field is not getting populated

### ISSUE THREAD

**Issue by cyntss** [EOS-uiux-Solutions/eos-icons-landing#10]
Importing issues from old repo on Gitlab.
Created by: @vinayaksh42 

----

The search field of the animated icons tab is not getting populated which results in the inability to share the icon as the URL remains the same.

https://user-images.githubusercontent.com/5013096/136406200-08fd2eed-8d72-4846-95ac-ee9cea02222a.mp4

**Comment by capedcrusader23** [comment]
if this is not resolved i can pick this up @cyntss .

**Comment by cyntss** [comment]
@capedcrusader23 all yours!
