### ISSUE TITLE
Feature Request: Toast message when we copy html tag

### ISSUE THREAD

**Issue by StarTrooper08** [EOS-uiux-Solutions/eos-icons-landing#112]
### Is your feature request related to a problem? Please describe.

When we copy the HTML tags for the specific icon. We don't get any message whether we have copied the icon tag or not.
![toastmsgfeature1SS](https://user-images.githubusercontent.com/72031540/158865340-6ce6fcb4-2354-40e0-b117-66d71e0d9b60.png)
.tags

### Describe the solution you'd like.

So I have added the toast msg feature when we copy the HTML tag we get toast msg on the top right side.
And it vanishes automatically after a few minutes.
![toastmsgfeature2SS](https://user-images.githubusercontent.com/72031540/158865598-af83eede-69d7-44ff-b20c-39b3653f8d21.png)

### Additional context.

Can I create PR for this issue? I have did the changes for the same.

**Comment by vinayaksh42** [comment]
@StarTrooper08 We already have an issue open for the same. https://github.com/EOS-uiux-Solutions/eos-icons-landing/issues/45

**Comment by StarTrooper08** [comment]
PR: https://github.com/EOS-uiux-Solutions/eos-icons-landing/pull/113#issue-1173291553

But it gives a build error in this file which I haven't changed
![error](https://user-images.githubusercontent.com/72031540/158961258-9ff311ce-952c-4043-8593-d801436c890c.png)
