### ISSUE TITLE
[BUG] Refreshing everything is breaking the UX

### ISSUE THREAD

**Issue by cyntss** [EOS-uiux-Solutions/eos-icons-landing#124]
When someone recently worked on the refresh event something broke. Now if i share a URL this gets cleaned up once I visit it.
Try it by going to :

https://eos-icons.com/?iconName=bootstrapping&type=static

then see that the URL would have cleaned now, so you can't copy-paste it again.

Additionally, something major is what happens when:
1- Search for an icon name, for instance, "pin"
2- Now click on the Pin icon

Results:
the search form is cleaning up (this is because the page is refreshing)
the URL isn't populating with the parameters to be able to share the Pin icon.

Can someone take this issue ASAP?

**Comment by ayushsatyam146** [comment]
I would like to work on this issue.

**Comment by ayushsatyam146** [comment]
I am planning to do the following -
1. Everything including URL and search params remain intact on refresh
2. Fix behaviour of clicking on icons after search
3. Retain the search and url params in a shared link
4. Implement auto scroll to selected Icon in a shared link( I need help for setting up the build for this issue)
