### ISSUE TITLE
[BUG] Website Domain is down

### ISSUE THREAD

**Issue by jagabomb** [EOS-uiux-Solutions/eos-icons-landing#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Domain is no longer working and Github pages url is not working either.

### Expected Behavior

Visit the url and see the landing page of icons.

### Steps To Reproduce

1. Visit either **https://eos-icons.com** or **https://eos-uiux-solutions.github.io/eos-icons-landing/**
2. Page is unable to load

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by cyntss** [comment]
Hi @jagabomb , thank you for this issue. We've deployed the site to Vercel. Here's the new domain
https://eos-icons-frontend-1t6flcbwl-eos-icons.vercel.app/

I've updated it in our documentation but if you find a new place where it should be updated, feel free to raise a PR and I'll approve it right away.

**Comment by jagabomb** [comment]
@cyntss Thanks for this. The new domain appears to be working. 😄
