### ISSUE TITLE
Enhancement: Add more meta tags

### ISSUE THREAD

**Issue by cyntss** [EOS-uiux-Solutions/eos-icons-landing#14]
Importing issues from old repo on Gitlab.
Created by: @Aman-Codes

----

Add more missing meta tags like description tags, keyword tags, Facebook and Twitter metadata tags etc.

**Comment by AnshumanDhiman** [comment]
Can I work on this @cyntss @kbhutani0001 @vinayaksh42

**Comment by AnshumanDhiman** [comment]
I have reviewed the code, meta tags are present in the index.html. However the primary meta tags are missing, the meta tags for twitter are not currently added and the description meta tag for facebook is also not added.
Current facebook meta tag will result in this : 
![f_meta](https://user-images.githubusercontent.com/67755381/154798327-0dfbb2ba-b3f2-47a5-a51c-3c948bc41d6d.jpg)
After adding the description it will look like this : 
![f_meta_fix](https://user-images.githubusercontent.com/67755381/154798335-a49c8933-983a-42b6-9f6e-d427e06206f9.jpg)
Adding the twitter meta tag will result in this : 
![t_meta](https://user-images.githubusercontent.com/67755381/154798343-e3942858-6190-4a0a-be95-6c03302e2385.jpg)

**Comment by cyntss** [comment]
this is a great fix @AnshumanDhiman !
