### ISSUE TITLE
Visiting other Pages renders with the scroll position of previously rendered Page

### ISSUE THREAD

**Issue by shrinishant** [EOS-uiux-Solutions/eos-icons-landing#24]
When visiting different Pages, the scroll position remains the same as the previously visited page. It should be scrolled to top of the page which the user clicks for better experience.

**Comment by shrinishant** [comment]
@cyntss I would like to work on this issue. Could you please assign this to me?

**Comment by vinayaksh42** [comment]
@shrinishant I have assigned you the issue
