### ISSUE TITLE
Bug: "Download Icon Bar" is not aligned properly

### ISSUE THREAD

**Issue by shagunchandra** [EOS-uiux-Solutions/eos-icons-landing#27]
The download icon bar takes up a lot of space and isn't properly placed under the animation icon area.
![Bug1](https://user-images.githubusercontent.com/84984600/151893976-642724ea-9a6b-4bbf-8a9e-54052df5141e.png)

**Comment by shagunchandra** [comment]
I am working on it.

**Comment by vinayaksh42** [comment]
Closing this issue as PR - https://github.com/EOS-uiux-Solutions/eos-icons-landing/pull/30 got merged
