### ISSUE TITLE
No result being shown when toggling between tabs 

### ISSUE THREAD

**Issue by capedcrusader23** [EOS-uiux-Solutions/eos-icons-landing#35]

**Comment by capedcrusader23** [comment]
will update more on this issue and try to figure out why it is happening again

**Comment by capedcrusader23** [comment]
While changing toggle we can see that no icons found appeared on static icons tabs. The selectMultiple field was only being used to check if tab is static or animated icons. Raised PR for this issue. 
<img width="1326" alt="Screenshot 2022-02-05 at 12 40 44 PM" src="https://user-images.githubusercontent.com/37747717/152632495-1b6bfc2c-7559-4cc6-b1cf-db2a69805814.png">
.

**Comment by vinayaksh42** [comment]
@capedcrusader23 can you make a short screen recorded video and reproduce the bug in the video?

**Comment by capedcrusader23** [comment]
https://user-images.githubusercontent.com/37747717/153048577-9f77dc70-0917-41e8-baef-f10445015e86.mov
