### ISSUE TITLE
Suggested search should have a pointer cursor

### ISSUE THREAD

**Issue by chinmaym07** [EOS-uiux-Solutions/eos-icons-landing#41]
Suggested search text shown should have a pointer cursor.

https://user-images.githubusercontent.com/44670961/153673873-f0ff8f8e-39ec-47cd-ac28-f0124f73aab7.mp4

**Comment by AnshumanDhiman** [comment]
can I work on this ?

**Comment by chinmaym07** [comment]
Yes you can work on this...  Once this issue is approved by maintainers .. Happy contributing ...!!
