### ISSUE TITLE
Various improvements

### ISSUE THREAD

**Issue by AnshumanDhiman** [EOS-uiux-Solutions/eos-icons-landing#44]
There are certain bugs which can be fixed in the eos-icons website.
1.The text "Implementation example" is mentioned twice. We can make it show only one.
![1](https://user-images.githubusercontent.com/67755381/154511371-8cb40b99-9855-401c-9186-967e21fae427.jpg)

2. These are some typos which can be fixed.
![image_2022-02-18_141400](https://user-images.githubusercontent.com/67755381/154648533-8df12d45-6593-41e5-a75d-c59a03c31f8a.png)

![3](https://user-images.githubusercontent.com/67755381/154511889-8967e2ac-b1dd-4cd0-81dd-e0ae78c742ae.jpg)
![2](https://user-images.githubusercontent.com/67755381/154511877-00680e5c-688e-4147-8bb3-485eb398d498.jpg)

3. We can add the GitHub repository link just after the "Go to our GitHub to find out more"
![4](https://user-images.githubusercontent.com/67755381/154512256-88e0ea73-17f7-4d41-89b4-ae43aeb5b762.jpg)

4. There is a broken link to Saurabh Sharma Sir's twitter account(saying the account does not exist when we open it). We can add the updated link.
![5](https://user-images.githubusercontent.com/67755381/154512470-8dc68b8a-6006-4d58-80d7-6e71d56dd97d.jpg)

5. Fix text and link mobile responsiveness issue(as here we can see colon is below with the link not with the text)
![6](https://user-images.githubusercontent.com/67755381/154513445-773e82df-77da-42e7-9f12-fcdf06150057.jpg)
![7](https://user-images.githubusercontent.com/67755381/154513453-8d30d40a-4dd1-4c44-b048-af97f1463e6a.jpg)
![8](https://user-images.githubusercontent.com/67755381/154513459-8676629a-2695-4c0d-9b9e-c94c352dc1e1.jpg)

**Comment by AnshumanDhiman** [comment]
Can I work on this if this issue is approved ?

**Comment by cyntss** [comment]
Amazing catch of so many small issues @AnshumanDhiman ! I'll assign you now. If you have too many please raise a flag and I will assign someone else. Thank you for your contribution!
