### ISSUE TITLE
Add a border around dropdown & reduce the space between down arrow icon & the text

### ISSUE THREAD

**Issue by chinmaym07** [EOS-uiux-Solutions/eos-icons-landing#46]
Down Arrow Icon & text are a little more separated & vertically misaligned due to which it looks like they both are different . 
Add a border & reduce the space between down arrow icon & the text.

Current Version:
![image](https://user-images.githubusercontent.com/44670961/154578141-6a410427-0ebe-4a83-bf13-e5f081b4485b.png)

Enhanced Version:
![image](https://user-images.githubusercontent.com/44670961/154578916-d5c07772-bc3e-4408-a07a-ee36180ec040.png)

**Comment by cyntss** [comment]
Can you use the same style as in our secondary buttons instead?
![image](https://user-images.githubusercontent.com/5013096/154674228-a61b78b1-0476-4b79-8022-40d262331987.png)

We need to follow the same UI and re-use classes to maintain consistency.
