### ISSUE TITLE
Various UI Improvements

### ISSUE THREAD

**Issue by AnshumanDhiman** [EOS-uiux-Solutions/eos-icons-landing#48]
There are certain UI improvements which can be made in the Eos icons.

1. The download eos icons is a bit far away from the text
![err1](https://user-images.githubusercontent.com/67755381/154654372-8f9cc49e-a62e-4b10-85ad-75bf8ae63c09.jpg)

Suggested Improvement : 
We can add the button just below the text to make it handy as shown
![fix1](https://user-images.githubusercontent.com/67755381/154654646-f94f16e7-2eb7-4bf1-a03d-497f364ab792.jpg)

2. There is a big gap present here and in certain points gap is needed to be provided.
![err3](https://user-images.githubusercontent.com/67755381/154655050-0d4f8fc5-074b-4b74-83b7-62f90db832f2.jpg)

3. The switch theme option is not available for the animated icons as shown.
https://user-images.githubusercontent.com/67755381/154658676-3c24b1b2-d688-4038-98c2-b9f9d23956e2.mp4

Suggested Improvement :
We can disable the switch to theme button for the animated icons.

**Comment by AnshumanDhiman** [comment]
If this issue is approved to be worked on can I work on it ?

**Comment by cyntss** [comment]
@AnshumanDhiman yes please! I'll assign you now
