### ISSUE TITLE
Bug: Error while searching two or more Icons at a time.

### ISSUE THREAD

**Issue by cyntss** [EOS-uiux-Solutions/eos-icons-landing#5]
Importing issues from old repo on Gitlab.
Created by: @Striver08

----

While searching two or more icons it shows "No Results to shows" but upon scrolling the page, Icons can be seen.   
PFA for reference.

![image](https://user-images.githubusercontent.com/5013096/136393808-3c100214-f503-4dc8-a971-2ece9bc5dd69.png)

![image](https://user-images.githubusercontent.com/5013096/136393847-517bd4ae-5770-4e98-9c97-edb8d57beb9b.png)

**Comment by capedcrusader23** [comment]
@cyntss  can you assign this to me.

**Comment by cyntss** [comment]
done @capedcrusader23
