### ISSUE TITLE
Reduce the Space between different types of icon section

### ISSUE THREAD

**Issue by chinmaym07** [EOS-uiux-Solutions/eos-icons-landing#53]
Empty space between different Icon sections is alot.

![Screenshot 2022-02-21 at 17-12-26 EOS free open source icons](https://user-images.githubusercontent.com/44670961/154949294-4034b71f-690f-4aa2-8eb3-75a89cb14c68.png)

**Comment by cyntss** [comment]
Sure @shagunchandra

**Comment by Abhirup-99** [comment]
![Screenshot from 2022-02-27 21-10-31](https://user-images.githubusercontent.com/48902681/155889172-5c9be334-eb8b-4958-8caf-8e2074c3b52a.png)

The space above `Action.js` is too less on mobile view.

**Comment by shagunchandra** [comment]
@Abhirup-99 I have fixed this, can you review my PR?
