### ISSUE TITLE
On Scrolling the codeblock overlaps with the navbar

### ISSUE THREAD

**Issue by chinmaym07** [EOS-uiux-Solutions/eos-icons-landing#55]
Codeblock  overlaps on scrolling in firefox browser . 
This works fine in different browsers like chrome, brave.
This is a browser specific issue.

https://user-images.githubusercontent.com/44670961/154952135-6f1f9947-a02e-4e20-bcd1-dd2c402bf85c.mp4

**Comment by vinayaksh42** [comment]
Thanks for reporting this issue @chinmaym07
