### ISSUE TITLE
when disable multiple choice, last element selected as part of multiple choice will still remain active & search result as well as uri remain empty

### ISSUE THREAD

**Issue by chinmaym07** [EOS-uiux-Solutions/eos-icons-landing#57]
**Steps to Reproduce**

Check the Select multiple icon input to true & select some icons then disable it, the last icon selected will be show as a selected icon which is fine but the search input & uri is empty .

https://user-images.githubusercontent.com/44670961/155037207-3864827c-fb18-4cf8-bd2d-e26c869b9054.mp4

**Comment by cyntss** [comment]
Good catch @chinmaym07

**Comment by shagunchandra** [comment]
@cyntss can I work on this?

**Comment by kbhutani0001** [comment]
Sure @shagunchandra take it up if @chinmaym07 isn't already working on it. Can you confirm @chinmaym07 ?

**Comment by chinmaym07** [comment]
Hey I am not working on this issue.. Feel free to take this up .. Happy Contributing . 🚀

**Comment by ayushsatyam146** [comment]
@kbhutani0001 I can take this up if no one else is assigned to it.

**Comment by ayushsatyam146** [comment]
@kbhutani0001 Made PR #84 regarding this issue. Please review.
