### ISSUE TITLE
Selection issue on Toggling to animated icons tab

### ISSUE THREAD

**Issue by cyntss** [EOS-uiux-Solutions/eos-icons-landing#6]
Importing issues from old repo on Gitlab.
Created by: @Sanyam_Pandey

----

If someone selects an icon in static icons and toggles to 'animated icon tab', the search results are shown according to icon selected in 'static icons tab' .Also the search bar shows the selected static icon name.

video:

https://gitlab.com/SUSE-UIUX/eos-icons-landing/uploads/2f7b2466342a35f935198cd1a6dcb805/screen-capture__13_.webm

**Comment by capedcrusader23** [comment]
i wanted to know the expected behaviour in this case. Ideally when an icon is selected in static tab and user switch to animated icons then all icons should be shown and if user switch back to static icons then previous selected icons should be selected right? @cyntss

**Comment by capedcrusader23** [comment]
can you assign this to me
