### ISSUE TITLE
Disable Switch theme input when Animated Icons Tab is active 

### ISSUE THREAD

**Issue by chinmaym07** [EOS-uiux-Solutions/eos-icons-landing#62]
Currently there is no functionality for Switch Theme in case of Animated Icons.

Solution 
Don't `hide` the Switch Theme input instead `Disable` it if the `Animated Icon` Tab is active

![image](https://user-images.githubusercontent.com/44670961/155222505-d30b5476-8d2e-4e47-85ff-6ad9f538b7b0.png)

**Comment by AnshumanDhiman** [comment]
Hi @chinmaym07 I am currently working on this issue, there is an active PR regarding this. Let me try this on my end and will let you know.

**Comment by chinmaym07** [comment]
Great ..thanks.
Do we have any other open issue that is used for tracking this change ?

**Comment by AnshumanDhiman** [comment]
yes #48 issue is active for this issue
