### ISSUE TITLE
Toggle "Select Multiple" to false when dealing with animated icons

### ISSUE THREAD

**Issue by cyntss** [EOS-uiux-Solutions/eos-icons-landing#7]
Importing issues from old repo on Gitlab.
Created by: @deutranium

----

### Current Behaviour:
The "Select Multiple" option does not toggle back to "off" state when a user is trying to select animated icons and gets disabled in the "on" state while preventing the user from selecting more than one icon. The same can be seen in the screenshot below

**Static Icons:**
![image](https://user-images.githubusercontent.com/5013096/136394564-5f45a142-9acf-48eb-8548-657b5b0e43c1.png)

**Animated Icons:**
![image](https://user-images.githubusercontent.com/5013096/136394575-0ce3cb89-6e72-4cc4-925d-4691aa36d2ba.png)

### Expected behaviour:
- Toggle in "on" state at "Static Icons" tab
    - Toggle should go to the "off" state and disabled when the user switches to the "Animated Icons" tab
    - Toggle should go back to the "on" state when the user goes back to the "Static Icons" tab
- Toggle in "off" state at "Static Icons" tab
    - Toggle should be in off state in both the tabs
    - Toggle should also be disabled in the "Animated Icons" tab

The same has been demonstrated in the form of the screenshots below:

**Static Icons:**
![image](https://user-images.githubusercontent.com/5013096/136394591-2eed4f7e-d612-4aca-8066-7b2f0dd3e125.png)

**Animated Icons:**
![image](https://user-images.githubusercontent.com/5013096/136394602-4a354634-1d85-4035-83c3-655dbcbc5d88.png)

### Possible fixes:

Following are a few fixes I thought of:
- Setting the toggle permanently to the "off" state and disabled when the user is on the "Animated Icons" tab
- Hiding the toggle when the user is on the "Animated Icons" tab

_P.S. I think it would also be better to give a message through a tooltip (for the first fix), or by replacing the toggle with an info icon (for the second fix), hovering/clicking on which the user gets a message telling them why multiple selections have been disabled. This is done because when I tried animated icons for the first time, I was pretty confused as to why I am not able to toggle the multiple selections._

**Comment by capedcrusader23** [comment]
@cyntss i would like to pick this issue.

**Comment by cyntss** [comment]
@capedcrusader23 all yours!

**Comment by capedcrusader23** [comment]
@cyntss , can you review this https://github.com/EOS-uiux-Solutions/eos-icons-landing/pull/18

**Comment by vinayaksh42** [comment]
Closing this issue as PR- https://github.com/EOS-uiux-Solutions/eos-icons-landing/pull/18 was merged
