### ISSUE TITLE
SEO issue: no twitter account added to the structure

### ISSUE THREAD

**Issue by cyntss** [EOS-uiux-Solutions/eos-icons-landing#8]
Importing issues from old repo on Gitlab.
Created by: @cyntss 

----

I passed eos-icons on woorank.com to get an analysis as to where we can improve it, and several issues where identified. among them, is this:

![image](https://user-images.githubusercontent.com/5013096/136405526-c6a2d8e7-cb26-44f4-8189-73c10eda5685.png)

More info provided by woorank

https://help.woorank.com/hc/en-us/articles/360000136385-Why-can-t-you-find-my-social-media-pages-

**Comment by kailash360** [comment]
@cyntss Can I work on this issue?

**Comment by cyntss** [comment]
@kailash360 go for it! 👍

**Comment by kailash360** [comment]
@cyntss 
I have created PR #17  for this issue
