### ISSUE TITLE
Fix default behaviour of eos-icons logo in Navbar

### ISSUE THREAD

**Issue by ayushsatyam146** [EOS-uiux-Solutions/eos-icons-landing#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user is present somewhere down on the Icons page, clicking the eos-icons logo in Navbar does nothing.

### Expected Behavior

Clicking the Navbar logo should restore the site to its default state i.e. how the site looks on the first-page load, clearing the How to use section, search and URL params.

### Steps To Reproduce

1. Open the site and scroll down.
2. Select any icon and try to click the logo in the Navbar

**Comment by vinayaksh42** [comment]
Can you give this issue a proper title?
