### ISSUE TITLE
Code color not rendering properly Docs/In Your Application

### ISSUE THREAD

**Issue by AnshumanDhiman** [EOS-uiux-Solutions/eos-icons-landing#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is a color scheme provided by prism-theme.scss which is used in code sections(where the links are stored). When we view the (in your application) page the code section shows colorful code, but as soon as we change to any other section such as (React) or (Vue) and then go back to (In your application) section then the colored code disappears. The prism-theme.scss file is loading correctly as there are changes which are implementing on state change but the text colors are disappearing.

https://user-images.githubusercontent.com/67755381/158101956-2b078c9c-2cf6-48ac-b0f9-73aa97d94435.mp4

### Expected Behavior

The colored code should be present if we switch back to the current state.

**Comment by AnshumanDhiman** [comment]
I would like to work on this.

**Comment by ayushsatyam146** [comment]
@vinayaksh42 if no one is working on this issue, I would like to pick this up.

**Comment by AnshumanDhiman** [comment]
@ayushsatyam146 I tried updating & fetching a fresh piece of code from provided by prism-theme but that didn't work out. Also I tried changing & providing a custom CSS to the block but that also didn't worked. This issue seems to be getting replicated when we change our sections from current docs section to in your application, on your computer etc.. but as soon we refresh the website (with the help of useEffect) the issue seems to be gone and once again if a user tries to access other section, the color code disappears. You can take this up and give it a try, meanwhile I'll also try to figure this out and communicate with you if anything works out.
